version: "1.0"

services:
  zookeeper:
    image: bitnami/zookeeper:3.8.0
    ports:
      - 2181:2181
    environment:
      - ZOO_PORT_NUMBER=2181
      - ZOO_TICK_TIME=2000
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - devenv
    
  kafka:
    image: bitnami/kafka:3.1.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=0
      - ALLOW_PLAINTEXT_LISTENER=yes
      - "KAFKA_HEAP_OPTS=-Xmx500m -Xms500m"
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=EXTERNAL://:9092,CLIENT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://localhost:9092,CLIENT://kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_MESSAGE_MAX_BYTES=3145729
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=3145729
    depends_on:
      - zookeeper
    networks:
      - devenv

  kafka-setup:
    image: bitnami/kafka:2.8.1
    hostname: kafka-setup
    container_name: kafka-setup
    depends_on:
      - kafka
    volumes:
      - ./topics:/topics.txt
      - ./create-topics.sh:/scripts/create-topics.sh
    command: bash /scripts/create-topics.sh
    environment:
      KAFKA_CFG_BROKER_ID: ignored
      KAFKA_CFG_ZOOKEEPER_CONNECT: ignored
    networks:
      - devenv
  
  get-kafka-exporter:
    image: busybox:1.35.0
    volumes:
      - exporters:/exporters
    command: wget --no-check-certificate https://repo1.maven.org/maven2/io/zeebe/zeebe-kafka-exporter/3.1.1/zeebe-kafka-exporter-3.1.1-jar-with-dependencies.jar -O /exporters/zeebe-kafka-exporter.jar

  zeebe:
    image: camunda/zeebe:8.2.1
    restart: always
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
    volumes:
      - ./config/zeebe/application.yaml:/usr/local/zeebe/config/application.yaml
      - exporters:/usr/local/zeebe/exporters
    depends_on:
      - kafka
      - get-kafka-exporter
    networks:
      - devenv

  zeebe-simple-monitor:
    image: ghcr.io/elisapolystar/zeebe-simple-monitor:latest
    restart: always
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.broker.gateway-address=zeebe:26500
      - PROFILE=kafka
      - spring.datasource.url=jdbc:postgresql://zeebe-test-bench-postgres-1:5432/postgres
      - spring.datasource.username=test
      - spring.datasource.password=password
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
    ports:
      - "8083:8082"
    depends_on:
      - zeebe
    networks:
      - devenv
  
  postgres:
    image: ghcr.io/cloudnative-pg/postgis:14-3.3
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgres/data
    networks:
      - devenv

volumes:
  exporters:
  postgres:

networks:
  devenv:
    driver: bridge
    name: devenv